// Game Constants & Configuration (Namespace Pattern)
window.Game = window.Game || {};

window.Game.VERSION = "v2.2.0 Mini-Boss Update";

window.Game.TEXTS = {
    EN: {
        SCORE: "SCORE", LEVEL: "LEVEL", LIVES: "LIVES", NORMAL: "NORMAL",
        INSERT_COIN: "INSERT COIN",
        START_HINT: "📱 TAP TO START • TOUCH SIDES MOVES • ICON SHIELDS",
        MOBILE_HINT: "📱 TOUCH SIDES to Move • ICON for Shield",
        PRO_TIP: "💎 PRO TIP: STOP MOVING TO HODL (2x SCORE)",
        WAVE1: "WAVE 1: ACCUMULATION", WAVE2: "WAVE 2: BULL RUN", WAVE3: "WAVE 3: VOLATILITY",
        BOSS_ENTER: "GOLD RESERVES", BOSS_DEATH: "RESERVES LIQUIDATED",
        GAME_OVER: "REKT", RESTART: "BUY THE DIP",
        COMBO_LOST: "COMBO LOST", COMBO_BREAK: "COMBO BREAK",
        UPGRADE: "UPGRADE LVL", MAX_POWER: "MAX POWER", HODL: "HODL!",
        SETTINGS: "SETTINGS", CLOSE: "CLOSE", LANG: "LANGUAGE",
        PAUSED: "PAUSED", RESUME: "RESUME", EXIT_TITLE: "EXIT TO TITLE"
    },
    IT: {
        SCORE: "PUNTI", LEVEL: "LIVELLO", LIVES: "VITE", NORMAL: "NORMALE",
        INSERT_COIN: "INSERISCI GETTONE",
        START_HINT: "📱 TOCCA PER INIZIARE • LATI: MUOVI • ICONA: SCUDO",
        MOBILE_HINT: "📱 TOCCA LATI: Muovi • ICONA: Scudo",
        PRO_TIP: "💎 PRO TIP: FERMATI PER HODL (Punti Doppi)",
        WAVE1: "ONDATA 1: ACCUMULO", WAVE2: "ONDATA 2: BULL RUN", WAVE3: "ONDATA 3: VOLATILITÀ",
        BOSS_ENTER: "RISERVE AUREE", BOSS_DEATH: "RISERVE LIQUIDATE",
        GAME_OVER: "REKT", RESTART: "COMPRA IL DIP",
        COMBO_LOST: "COMBO PERSA", COMBO_BREAK: "COMBO ROTTA",
        UPGRADE: "POTENZIAMENTO LV", MAX_POWER: "MASSIMA POTENZA", HODL: "HODL!",
        SETTINGS: "IMPOSTAZIONI", CLOSE: "CHIUDI", LANG: "LINGUA",
        PAUSED: "PAUSA", RESUME: "RIPRENDI", EXIT_TITLE: "ESCI AL TITOLO"
    }
};

window.Game.MEMES = {
    // General Crypto Culture
    LOW: [
        "HODL", "BUY THE DIP", "SHITCOIN", "PAPER HANDS", "NGMI", "HFSP",
        "FUD DETECTED", "REKT", "WAGMI", "LFG", "APE IN", "DEGEN MODE",
        "PUMP IT", "DUMP IT", "SEND IT", "NFA", "DYOR", "FOMO ENGAGED",
        "COPE HARDER", "HAVE FUN STAYING POOR", "FEW UNDERSTAND",
        "THIS IS THE WAY", "PROBABLY NOTHING", "BULLISH AF",
        "FLOOR IS LAVA", "UP ONLY", "NUMBER GO UP", "STACK SATS",
        "NOT YOUR KEYS", "NOT YOUR COINS", "TRUST THE PROCESS",
        "ZOOM OUT", "TIME IN MARKET", "DCA IS THE WAY"
    ],
    HIGH: [
        "TO THE MOON 🚀", "LAMBO SOON", "WHALE ALERT 🐋", "DIAMOND HANDS 💎",
        "WE'RE ALL GONNA MAKE IT", "GENERATIONAL WEALTH", "EARLY ADOPTER",
        "MICHAEL SAYLOR MODE", "LASER EYES ACTIVATED", "STILL EARLY",
        "FUTURE MILLIONAIRE", "GIGACHAD MOVE", "ABSOLUTE UNIT",
        "CONVICTION LEVEL: MAX", "NEVER SELLING", "INFINITY HODL",
        "APEX PREDATOR", "MONETARY MAXIMALIST", "FREEDOM TECHNOLOGY"
    ],
    // Michael Saylor Quotes
    SAYLOR: [
        "BITCOIN IS HOPE",
        "BITCOIN IS DIGITAL GOLD",
        "BITCOIN IS A SWARM OF CYBER HORNETS",
        "THERE IS NO SECOND BEST",
        "BITCOIN IS THE APEX PREDATOR",
        "INFINITY DIVIDED BY 21 MILLION",
        "BTC IS DIGITAL ENERGY",
        "BITCOIN IS ECONOMIC IMMORTALITY",
        "BITCOIN IS THERMODYNAMICALLY SOUND",
        "BITCOIN FIXES THIS",
        "EVERY COMPANY WILL HOLD BITCOIN",
        "BITCOIN IS A MONETARY NETWORK",
        "BUY BITCOIN AND WAIT",
        "BITCOIN IS DIGITAL PROPERTY",
        "BITCOIN IS THE HARDEST ASSET",
        "BITCOIN IS INCORRUPTIBLE",
        "BITCOIN IS THE EXIT",
        "HYPERBITCOINIZATION INCOMING",
        "BITCOIN IS PURE ENERGY",
        "THE GREAT REPRICING",
        "BITCOIN IS TRUTH",
        "BITCOIN NEVER SLEEPS",
        "BITCOIN IS STRONGER THAN GOVERNMENTS",
        "SELLING BTC IS SELLING THE FUTURE",
        "BITCOIN IS MONETARY INTEGRITY",
        "BITCOIN IS ENGINEERED MONEY",
        "BITCOIN IS THE RATIONAL CHOICE",
        "BITCOIN IS CIVILIZATION'S BATTERY",
        "BITCOIN ABSORBS VALUE",
        "BITCOIN IS PERFECT MONEY",
        "BITCOIN IS FREEDOM",
        "BITCOIN IS YOUR LIFEBOAT",
        "BITCOIN IS DIGITAL SCARCITY",
        "BITCOIN IS A FORCE OF NATURE",
        "BITCOIN TRANSCENDS NATIONS",
        "SAYLOR'S STACKING",
        "MICROSTRATEGY APPROVED",
        "21M OR BUST",
        "VOLATILITY IS VITALITY",
        "BITCOIN IS A CERTAINTY IN CHAOS",
        "BITCOIN IS ETHICAL MONEY",
        "BITCOIN HUMBLES YOU",
        "BITCOIN IS PURE MATHEMATICS",
        "BITCOIN IS A LIVING ORGANISM",
        "BITCOIN ABSORBS ALL",
        "BITCOIN IS INCORRUPTIBLE MATH",
        "BITCOIN IS THE ANTIDOTE",
        "BITCOIN: THE FINAL BOSS",
        "BITCOIN DOESN'T CARE",
        "STACK SATS OR DIE TRYING"
    ],
    // Fiat/Enemy Death Taunts
    FIAT_DEATH: [
        "INFLATION CANCELLED", "FIAT DESTROYED", "MONEY PRINTER JAMMED",
        "CENTRAL BANK REKT", "FED IS DED", "EURO ZEROED", "YEN YEETED",
        "POUND POUNDED", "DOLLAR DEMOLISHED", "CURRENCY CRUSHED",
        "DEBASEMENT DENIED", "PRINTER GO BRRR... ERROR", "FIAT FATAL ERROR",
        "PURCHASING POWER PRESERVED", "HARD MONEY WINS"
    ],
    // Boss Taunts
    BOSS: [
        "INFLATION BOSS FIGHT", "THE FED AWAKENS", "MONEY PRINTER: FINAL FORM",
        "CENTRAL BANK SHOWDOWN", "RESERVE STATUS: THREATENED",
        "QUANTITATIVE EASING: MAXIMUM", "DEBT CEILING: BREACHED",
        "PONZI SCHEME DETECTED", "FIAT ENDGAME", "THE GREAT RESET"
    ],
    // Streak Multiplier
    STREAK: [
        "NICE ENTRY", "WHALE ALERT", "LIQUIDATION SPREE", "MARKET MAKER",
        "ABSOLUTE UNIT", "GOD MODE", "SATOSHI REBORN", "UNSTOPPABLE",
        "ON FIRE", "MEGA KILL", "ULTRA KILL", "LEGENDARY", "GODLIKE"
    ]
};

window.Game.WEAPONS = {
    NORMAL: { color: '#F7931A', rate: 0.18 },
    RAPID: { color: '#3498db', rate: 0.08, icon: '🚀' },
    SPREAD: { color: '#9b59b6', rate: 0.25, icon: '🔱' },
    LASER: { color: '#e74c3c', rate: 0.35, icon: '⚡' }
};

window.Game.FIAT_TYPES = [
    { s: '¥', c: '#bdc3c7', val: 30, hp: 1, fireMin: 3.0, fireMax: 4.5, aimSpread: 0.28, pattern: 'SINGLE' },
    { s: '€', c: '#3498db', val: 50, hp: 1, fireMin: 2.6, fireMax: 3.8, aimSpread: 0.22, pattern: 'BURST' },
    { s: '£', c: '#9b59b6', val: 50, hp: 1, fireMin: 2.2, fireMax: 3.2, aimSpread: 0.18, pattern: 'SINGLE' },
    { s: '$', c: '#2ecc71', val: 100, hp: 1, fireMin: 1.8, fireMax: 2.8, aimSpread: 0.14, pattern: 'DOUBLE' }
];

window.Game.SHIPS = {
    BTC: { speed: 420, hp: 3, fireRate: 0.18, color: '#F7931A', hitboxSize: 30 },
    ETH: { speed: 320, hp: 4, fireRate: 0.40, color: '#8c7ae6', hitboxSize: 38 },
    SOL: { speed: 560, hp: 2, fireRate: 0.14, color: '#00d2d3', hitboxSize: 18 }
};

window.Game.ASSETS = {};

window.Game.M_CHARS = "01BTCETH$$£€¥HODL";

